{{- if .Values.olmv1.enabled }}
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: sandboxed-containers
spec:
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  serviceAccount:
    name: sandboxed-containers-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: {{ .Values.olmv1.packageName }}
      channels:
        - {{ .Values.olmv1.channel }}
      name: {{ if .Values.dev.enabled }}{{ .Values.olmv1.catalogName }}{{ else }}openshift-redhat-operators{{ end }}
      upgradeConstraintPolicy: CatalogProvided
{{- end }}
