{{- if .Values.olmv1.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandboxed-containers-installer
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
{{- end }}
